version: '3.8'

services:
  db:
    image: mariadb:latest
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wordpress-network
    restart: unless-stopped

  wordpress:
    image: wordpress:latest
    ports:
      - "8080:80"
    env_file:
      - .env
    volumes:
      - ./wordpress:/var/www/html
      - ./php.ini:/usr/local/etc/php/php.ini
    networks:
      - wordpress-network
    depends_on:
      - db
    restart: unless-stopped

  nginx:
    build:
      context: .
      dockerfile: ./deploy/nginx/Dockerfile.nginx
    command: nginx -g 'daemon off;'
    volumes:
      - ./deploy/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./wordpress:/var/www/html
    depends_on:
      - wordpress
    networks:
      - wordpress-network
    restart: unless-stopped

  nginx_proxy_pass:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - nginx_data:/data
      - letsencrypt_data:/etc/letsencrypt

volumes:
  db_data:
  nginx_data:
  letsencrypt_data:

networks:
  wordpress-network:
